
#Test.animals = read.csv("test.csv.gz.csv", header = T)
All.data = read.csv('train.csv.gz', header = T)
# Attaching other files
All.data$SimpleBreed = as.character(All.data$Breed)
All.data$SimpleBreed = as.character(All.data$SimpleBreed)
All.data$SimpleBreed =sapply(All.data$SimpleBreed, function(x) gsub(' Mix', '', strsplit(x, split = '/')[[1]][1]))
Extra = read.csv('Extra Files.csv', header = T)
#Lifespan = read.csv('Breed Lifespans.csv', header = T)
#Hunting = unique(Hunting)
#Lifespan = unique(Lifespan)
#Lifespan$AVERAGE.LIFESPAN..YEARS. = ifelse(Lifespan$Breed == 'Yorkshire Terrier', 13, Lifespan$AVERAGE.LIFESPAN..YEARS.)
#Lifespan$AVERAGE.LIFESPAN..YEARS. = ifelse(Lifespan$Breed == 'Tonkinese', 15, Lifespan$AVERAGE.LIFESPAN..YEARS.)
#Lifespan = unique(Lifespan)
All.data = merge(x=All.data, y = Extra, by.x = "SimpleBreed", by.y ="Breed", all.x=TRUE, incomparables = 'Unknown')
All.data = All.data[All.data$SimpleBreed != 'Unknown',]

# ----- Recoding -----
library(dplyr)
All.data$AnimalID = (1:26727)

# Names
All.data$Name = ifelse(is.na(All.data$Name), 'No', 'Yes')

# Sex
All.data = mutate(All.data, Sex = ifelse(All.data$SexuponOutcome == 'Spayed Female' | All.data$SexuponOutcome == 'Intact Female','Female', All.data$Sex))
All.data = mutate(All.data, Sex = ifelse(All.data$SexuponOutcome == 'Neutered Male' | All.data$SexuponOutcome == 'Intact Male', 'Male', All.data$Sex))
All.data = mutate(All.data, Fixed = ifelse(All.data$SexuponOutcome == 'Spayed Female' | All.data$SexuponOutcome == 'Neutered Male', 'Yes', All.data$SexuponOutcome))
All.data = mutate(All.data, Fixed = ifelse(All.data$SexuponOutcome == 'Intact Female' | All.data$SexuponOutcome == 'Intact Male', 'No', All.data$Fixed))
All.data$Sex = ifelse(All.data$Sex == '', 'Unknown', All.data$Sex)
All.data$Fixed = ifelse(All.data$Fixed == '', 'Unknown', All.data$Fixed)
All.data$Sex = ifelse(All.data$Fixed == 6, 'Unknown', All.data$Sex)
All.data$Sex = ifelse(All.data$Fixed == 1, 'Unknown', All.data$Sex)
All.data$Fixed = ifelse(All.data$Fixed == 6, 'Unknown', All.data$Fixed)
table(All.data$Sex)

# Age
All.data$Age = ifelse(grepl('week', All.data$AgeuponOutcome), 'Baby', All.data$AgeuponOutcome)
All.data$Age = ifelse(grepl('day', All.data$AgeuponOutcome), 'Baby', All.data$Age)
All.data$Age = ifelse(grepl('month', All.data$AgeuponOutcome), 'Baby', All.data$Age)
All.data$Age = ifelse(grepl('0 years', All.data$AgeuponOutcome), 'Baby', All.data$Age)
All.data = mutate(All.data, Age = ifelse(All.data$Age == '1 year' 
                                         | All.data$Age == '2 years'
                                         | All.data$Age == '3 years' | All.data$Age == '4 years' | All.data$Age == '5 years'
                                         | All.data$Age == '6 years', 'Adult', All.data$Age))
All.data$Age = ifelse(grepl('years', All.data$Age), 'Senior', All.data$Age)
All.data = mutate(All.data, Age = ifelse(All.data$Age == 'Adult' | All.data$Age == 'Senior' | All.data$Age == 'Baby', All.data$Age, 'Unknown'))

table(All.data$AgeuponOutcome)


All.data$AgeuponOutcome = as.character(All.data$AgeuponOutcome)
All.data$TimeValue = sapply(All.data$AgeuponOutcome, function(x) strsplit(x,split = ' ') [[1]][1])
All.data$UnitofTime = sapply(All.data$AgeuponOutcome, function(x) strsplit(x,split = ' ') [[1]][2])
#Get Rid of Plurals on the Units of time. e.g. Turn "Years" into "Year"
All.data$UnitofTime <-gsub('s', '', All.data$UnitofTime) 
All.data$TimeValue <- as.numeric(All.data$TimeValue)
#Standardize across ages 
Multiplier = ifelse(All.data$UnitofTime == 'day',1, ifelse(All.data$UnitofTime =='week', 7, ifelse(All.data$UnitofTime =='month', 30, ifelse(All.data$UnitofTime == 'year', 365, NA))))
All.data$AgeinDays = All.data$TimeValue * Multiplier
summary(All.data$AgeinDays)
All.data$AgeinDays = as.factor(All.data$AgeinDays)
library(Hmisc)
#install.packages('rpart')
library(rpart)
All.data$AgeinDays = as.numeric(as.character(All.data$AgeinDays))
sum(is.na(All.data$AgeinDays))
age_fit = rpart(AgeinDays ~ AnimalType + Sex+ Fixed + SimpleBreed+ Name, 
              data = All.data[!is.na(All.data$AgeinDays), ],
               method = 'anova')

#Put predicted values into missing values 
All.data$AgeinDays[is.na(All.data$AgeinDays)] = predict(age_fit, All.data[is.na(All.data$AgeinDays),])
sum(is.na(All.data$AgeinDays))

#All.data = All.data[-c(4)]
# Mix or full
All.data$Mix = ifelse(grepl('Mix', All.data$Breed), 'Yes', All.data$Breed)
All.data$Mix = ifelse(grepl('/', All.data$Breed), 'Yes', All.data$Mix)
All.data = mutate(All.data, Mix = ifelse(All.data$Mix == 'Yes', 'Yes', 'No'))


# Breed
Cats = All.data[All.data$AnimalType == 'Cat',]
Dogs = All.data[All.data$AnimalType == 'Dog',]
PredictCatGender = Cats[Cats$Color =='Calico' | Cats$Color == 'Tricolor' | Cats$Color == 'Torbie' | Cats$Color == 'Tortie',]
NotCatGender = Cats[Cats$Color !='Calico' & Cats$Color != 'Tricolor' & Cats$Color != 'Torbie' & Cats$Color != 'Tortie',]
table(PredictCatGender$Sex)
PredictCatGender = mutate(PredictCatGender, Sex = ifelse(PredictCatGender$Sex == 'Male', 'Male', 'Female'))
Cats = bind_rows(PredictCatGender, NotCatGender)
# Hypo
Dogs$Hypo = Dogs$Breed
Dogs = mutate(Dogs, Hypo = ifelse(Dogs$Hypo == 'Labrador' | Dogs$Hypo == 'Golden Retriever' | Dogs$Hypo == 'Siberian Husky', 0, Dogs$Hypo))

Dogs$Hypo = ifelse(grepl('Poodle', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Yorkshire', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Havanese', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Maltese', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Shih Tzu', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Schnauzer', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Basenji', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Silky Terrier', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Irish Water Spaniel', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Terrier', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Terr', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Afghan Hound', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Water Spaniel', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Spanish Water', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Water Dog', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl('Bichon Frise', Dogs$Hypo), 1, Dogs$Hypo)
Dogs$Hypo = ifelse(grepl(1, Dogs$Hypo), 1, 0)

Cats$Hypo = Cats$Breed
Cats$Hypo = ifelse(grepl('Siberian', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Balinese', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Bengal', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Burmese', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Siberian', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Cornish Rex', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Devon Rex', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Javanese', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Ocicat', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Russian Blue', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Siamese', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl('Sphynx', Cats$Hypo), 1, Cats$Hypo)
Cats$Hypo = ifelse(grepl(1, Cats$Hypo), 1, 0)

# Size
# Small < 25 lbs
# Medium 25 < x < 50 lbs
# Large 50 < x < 100 lbs
table(Dogs$Breed)
Dogs$Size = Dogs$Breed
Dogs$Size = as.character(Dogs$Size)
Dogs$Size = sapply(Dogs$Size, 
                   function(x) gsub(' Mix', ' ',
                                    strsplit(x, split = ' Mix')[[1]][1]))
Dogs$Size = ifelse(grepl('Miniature', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Mini', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Toy', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Chihuahua', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Dachshund', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Maltese', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Pomeranian', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Shih Tzu', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Yorkshire Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Havanese', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Coonhound', Dogs$Size), 'Large', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Pug' | Dogs$Size == 'Boston Terrier', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Dandie Dinmont' | Dogs$Size == 'Coton De Tulear' | Dogs$Size == 'Cavalier Span' | Dogs$Size == 'Chinese Crested', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Bruss Griffon' | Dogs$Size == 'Bedlington Terr' | Dogs$Size == 'Bichon Frise' | Dogs$Size == 'Affenpinscher', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Japanese Chin' | Dogs$Size == 'Finnish Spitz' | Dogs$Size == 'Feist' | Dogs$Size == 'Manchester Terrier', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Schipperke' | Dogs$Size == 'Podengo Pequeno' | Dogs$Size == 'Patterdale Terr' | Dogs$Size == 'Manchester Terrier', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Bichons Frise' | Dogs$Size == 'West Highland Terrier' | Dogs$Size == 'Papillon' | Dogs$Size == 'Silky Terrier', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Jack Russell Terrier' | Dogs$Size == 'Cavalier King Charles Spaniel' | Dogs$Size == 'Beagle' | Dogs$Size == 'Shetland Sheepdog', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Welsh Terrier' | Dogs$Size == 'Swedish Vallhund' | Dogs$Size == 'Sealyham Terr' | Dogs$Size == 'Scottish Terrier', 'Small', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Border Collie' | Dogs$Size == 'Brittany' | Dogs$Size == 'Golden Rretriever' | Dogs$Size == 'English Shepherd', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'American Water Spaniel' | Dogs$Size == 'Australian Cattle Dog' | Dogs$Size == 'Australian Shepherd' | Dogs$Size == 'Basenji', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Barbet' | Dogs$Size == 'Basset Hound' | Dogs$Size == 'Cardigan Welsh Corgi' | Dogs$Size == 'Dalmatian', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Chinese Sharpei' | Dogs$Size == 'Boykin Span' | Dogs$Size == 'Carolina Dog' | Dogs$Size == 'Blue Lacy', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Welsh Springer Spaniel' | Dogs$Size == 'Treeing Tennesse Brindle' | Dogs$Size == 'Treeing Cur' | Dogs$Size == 'Skye Terrier', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Bulldog' | Dogs$Size == 'Cocker Spaniel' | Dogs$Size == 'Standard Schnauzer' | Dogs$Size == 'Samoyed', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Jindo' | Dogs$Size == 'German Pinscher' | Dogs$Size == 'Field Spaniel' | Dogs$Size == 'English Springer Spaniel', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Port Water Dog' | Dogs$Size == 'Pbgv' | Dogs$Size == 'Mexican Hairless' | Dogs$Size == 'Keeshond', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Afghan Hound' | Dogs$Size == 'Airedale Terrier' | Dogs$Size == 'Akita' | Dogs$Size == 'American Foxhound', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Bloodhound' | Dogs$Size == 'Belgian Sheepdog' | Dogs$Size == 'Boxer' | Dogs$Size == 'Bull Terrier', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Chow Chow' | Dogs$Size == 'Golden Retriever' | Dogs$Size == 'English Setter' | Dogs$Size == 'German Shepherd', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Labrador Retriever' | Dogs$Size == 'Rottweiler' | Dogs$Size == 'Siberian Husky' | Dogs$Size == 'Standard Poodle', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Bernese Mountain Dog' | Dogs$Size == 'Greyhound' | Dogs$Size == 'Foxhound' | Dogs$Size == 'Belgian Tervuren', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Spinone Italiano' | Dogs$Size == 'Schnauzer Giant' | Dogs$Size == 'Plott Hound' | Dogs$Size == 'Picardy Sheepdog', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Hovawart' | Dogs$Size == 'Ibizan Hound' | Dogs$Size == 'Harrier' | Dogs$Size == 'Gordon Setter', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Dutch Shepherd/Anatol Shepherd' | Dogs$Size == 'Dogue De Bordeaux/American Bulldog' | Dogs$Size == 'Doberman Pinsch' | Dogs$Size == 'Dutch Shepherd/Boxer', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Black/Tan Hound' | Dogs$Size == 'Belgian Malinois' | Dogs$Size == 'Beauceron' | Dogs$Size == 'American Bulldog', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Chesa Bay Retr' | Dogs$Size == 'Bluetick Hound' | Dogs$Size == 'Dogo Argentino/Chinese Sharpei' | Dogs$Size == 'Dalmatian/Basset Hound', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Entlebucher' | Dogs$Size == 'English Foxhound' | Dogs$Size == 'Dutch Shepherd' | Dogs$Size == 'Dogo Argentino', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Saluki' | Dogs$Size == 'Saluki/Doberman Pinsch' | Dogs$Size == 'Otterhound' | Dogs$Size == 'Nova Scotia Duck Tolling Retriever', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Wirehaired Pointing Griffon', 'Large', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Black' | Dogs$Size == 'Great Dane' | Dogs$Size == 'Great Pyrenees' | Dogs$Size == 'Irish Wolfhound', 'XL', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Saint Bernard' | Dogs$Size == 'Mastiff' | Dogs$Size == 'Newfoundland' | Dogs$Size == 'Leonberger', 'XL', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Presa Canario' | Dogs$Size == 'Landseer', 'XL', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Dogue De Bordeaux' | Dogs$Size == 'Cane Corso' | Dogs$Size == 'Anatol Shepherd', 'XL', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Greater Swiss Mountain Dog' | Dogs$Size == 'Bullmastiff' | Dogs$Size == 'Boerboel' | Dogs$Size == 'Kuvasz', 'XL', Dogs$Size))
# Mixes -- Run in this order
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'German Shepherd/Cardigan Welsh Corgi', 'Medium', Dogs$Size))
Dogs$Size = ifelse(grepl('German Shepherd', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('French Bulldog', Dogs$Size), 'Small', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Flat Coat Retriever/Papillon', 'Small', Dogs$Size))
Dogs$Size = ifelse(grepl('Flat Coat Retriever', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('St. Bernard Rough Coat/Border Collie', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('St. Bernard', Dogs$Size), 'XL', Dogs$Size)
Dogs$Size = ifelse(grepl('Staffordshire', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Whippet/Labrador Retriever', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Whippet', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Siberian Husky/Great Pyranees', Dogs$Size), 'Large', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Siberian Husky/Labrador Retriever'| Dogs$Size == 'Siberian Husky/Catahoula'| Dogs$Size == 'Siberian Husky/Rottweiler' | Dogs$Size == 'Siberian Husky/Alaskan Malamute', 'Large', Dogs$Size ))
Dogs$Size = ifelse(grepl('Siberian Husky/Anatol Shepherd', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Siberian Husky', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Fox Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Mastiff', Dogs$Size), 'XL', Dogs$Size)
Dogs$Size = ifelse(grepl('West Highland', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Vizsla/Beagle', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Vizsla', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Shiba Inu', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Wheaten Terrier', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Weimaraner', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Shetland Sheepdog/Keeshold', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Shetland Sheepdog', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Rottweiler', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Rhod Ridgeback', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Redbone Hound', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Rat Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Queensland Heeler/Great Dane', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Queensland Heeler', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Tibetan', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Jack Russell Terrier/Labrador Retriever', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Jack Russell Terrier/Pointer', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Jack Russell Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Labrador Retriever/Beagle' | Dogs$Size == 'Labrador Retriever/Blue Lacy' | Dogs$Size == 'Labrador Retriever/Black Mouth Cur' | Dogs$Size == 'Labrador Retriever/Boston Terrier' | Dogs$Size == 'Labrador Retriever/Border Terrier', 'Medium', Dogs$Size))
Dogs$Size = ifelse(grepl('Labrador Retriever', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Great Pyranees/Border Collie', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Great', Dogs$Size), 'XL', Dogs$Size)
Dogs$Size = ifelse(grepl('Pug/Pit Bull', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Pit Bull/Pug', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Pug', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Pointer', Dogs$Size), 'Medium', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Pit Bull/Border Collie' | Dogs$Size == 'Pit Bull/Blue Lacy' | Dogs$Size == 'Pit Bull/Black Mouth Cur' | Dogs$Size == 'Pit Bull/Boston Terrier' | Dogs$Size == 'Pit Bull/Border Terrier', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Pit Bull/Beagle' | Dogs$Size == 'Pit Bull/Carolina Dog' | Dogs$Size == 'Pit Bull/Cardigan Welsh Corgi' | Dogs$Size == 'Pit Bull/English Bulldog' | Dogs$Size == 'Pit Bull/American Bull Dog', 'Medium', Dogs$Size))
Dogs$Size = ifelse(grepl('Pit Bull', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Pembroke Welsh Corgi/Brittany', Dogs$Size), 'Small', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Pembroke Welsh Corgi', 'Small', Dogs$Size))
Dogs$Size = ifelse(grepl('Pembroke Welsh Corgi', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Standard Schnauzer', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Plott Hound', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Pharaoh Hound', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Scottish Terrier/Basset Hound', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Scottish Terrier/Cairn Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Australian', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Alaskan', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Papillon', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Russell Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Pekingese', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Norwich Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Old English', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Norfolk Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Golden Retriever/Chow Chow' | Dogs$Size == 'Golden Retriever/Standard Poodle' | Dogs$Size == 'Akita', 'Large', Dogs$Size))
Dogs$Size = ifelse(grepl('Golden Retriever', Dogs$Size), 'Medium', Dogs$Size)
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Catahoula/Cardigan Welsh Corgi' | Dogs$Size == 'Catahoula/Border Collie' | Dogs$Size == 'Catahoula/American Bulldog', 'Medium', Dogs$Size))
Dogs = mutate(Dogs, Size = ifelse(Dogs$Size == 'Catahoula/Beagle' | Dogs$Size == 'Catahoula/Black Mouth Cur', 'Medium', Dogs$Size))
Dogs$Size = ifelse(grepl('Catahoula', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Lhasa Apso', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Lowchen', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Nova Scotia Duck Tolling Retriever/Border Collie', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Norwegian Elkhound', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Newfoundland/Border Collie', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Manchester Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Italian Greyhound', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Irish Wolfhound', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Irish Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Greyhound', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Glen Of Imaal', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('English Bulldog/Boxer', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('English Bulldog', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Collie Smooth/Beagle', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Collie', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('English Springer Spaniel', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Cocker Spaniel', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Boxer', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Cairn Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Border Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('American Bulldog', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Corgi', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Chow Chow', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Boston Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Beagle/Cavalier Span', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Beagle', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Black Mouth Cur', Dogs$Size), 'Large', Dogs$Size)
Dogs$Size = ifelse(grepl('Border Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Chinese Sharpei', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('Canaan Dog', Dogs$Size), 'Medium', Dogs$Size)
Dogs$Size = ifelse(grepl('American Eskimo', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Border Terrier', Dogs$Size), 'Small', Dogs$Size)
Dogs$Size = ifelse(grepl('Basset Hound', Dogs$Size), 'Large', Dogs$Size)
table(Dogs$Size)

Cats$Size = Cats$Breed
Cats$Size = as.character(Cats$Breed)
Cats$Size = sapply(Cats$Size, 
                   function(x) gsub(' Mix', ' ',
                                    strsplit(x, split = ' Mix')[[1]][1]))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'British Shorthair' | Cats$Size == 'Ocicat' | Cats$Size == 'Chartreux' | Cats$Size == 'Norwegian Forest Cat', 'Large', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Turkish Van' | Cats$Size == 'Pixiebob Shorthair' | Cats$Size == 'Himalayan' | Cats$Size == 'American Wirehair', 'Large', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'American Shorthair', 'Large', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Persian' | Cats$Size == 'Abyssinian' | Cats$Size == 'Sphynx' | Cats$Size == 'Siamese', 'Medium', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Exotic Shorthair' | Cats$Size == 'Scottish Fold' | Cats$Size == 'Cornish Rex' | Cats$Size == 'Devon Rex', 'Medium', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Burmese' | Cats$Size == 'Tonkinese' | Cats$Size == 'Russian Blue' | Cats$Size == 'Manx', 'Medium', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Japanese Bobtail' | Cats$Size == 'Turkish Angora' | Cats$Size == 'Balinese' | Cats$Size == 'Bombay', 'Medium', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Havana Brown' | Cats$Size == 'Bengal' | Cats$Size == 'Cymric' | Cats$Size == 'Snowshoe', 'Medium', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Maine Coon' | Cats$Size == 'Ragdoll', 'XL', Cats$Size))
Cats = mutate(Cats, Size = ifelse(Cats$Size == 'Large' | Cats$Size == 'XL', Cats$Size, 'Medium'))

# Hair Length
Cats$Hair = ifelse(grepl('Shorthair', Cats$Breed), 'Short', Cats$Breed)
Cats$Hair = ifelse(grepl('Medium Hair', Cats$Breed), 'Medium', Cats$Hair)
Cats$Hair = ifelse(grepl('Longhair', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Persian', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Maine Coon', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Norwegian', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Balinese', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Sphynx', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Ragdoll', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Siamese', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Abyssinian', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Burmese', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Tonkinese', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Havana', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Snowshoe', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Russian Blue', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Manx', Cats$Breed), 'Medium', Cats$Hair)
Cats$Hair = ifelse(grepl('Bengal', Cats$Breed), 'Medium', Cats$Hair)
Cats$Hair = ifelse(grepl('Turkish Van', Cats$Breed), 'Medium', Cats$Hair)
Cats$Hair = ifelse(grepl('Angora', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Himalayan', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Bobtail', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Wirehair', Cats$Breed), 'Medium', Cats$Hair)
Cats$Hair = ifelse(grepl('Bombay', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Chartreux', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Cornish', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Cymric', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Devon', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Javanese', Cats$Breed), 'Long', Cats$Hair)
Cats$Hair = ifelse(grepl('Ocicat', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Oriental', Cats$Breed), 'Short', Cats$Hair)
Cats$Hair = ifelse(grepl('Scottish', Cats$Breed), 'Short', Cats$Hair)
Dogs$Breed = as.character(Dogs$Breed)
Dogs$Breed = sapply(Dogs$Breed, 
                    function(x) gsub(' Mix', '', 
                                     strsplit(x, split = '/')[[1]][1]))

Dogs$Hair = ifelse(grepl('Affenpinscher', Dogs$Breed), 'Short', Dogs$Breed)
Dogs$Hair = ifelse(grepl('Beagle', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('American Foxhound', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Basenji', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Basset Hound', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Beauceron', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Australian Cattle Dog', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bulldog', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Boxer', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bearded Collie', Dogs$Breed), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Chihuahua', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Dachshund Longhair', Dogs$Breed), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Dachshund', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bloodhound', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Dalmatian', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Beagle', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Labrador', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('German Shepherd', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Great Dane', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Shorthair', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Retriever', Dogs$Breed), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Greyhound', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Dutch Shepherd', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Wire Hair Fox Terrier', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pit Bull', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bearded Collie', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Yorkshire Terrier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bearded Collie', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Afghan Hound', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Havanese', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bernese Mountain Dog', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Lhasa Apso', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Shih Tzu', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Maltese', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pomeranian', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Rottweiler', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Husky', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Poodle', Dogs$Breed), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Airedale Terrier', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bearded Collie', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Border Collie', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Australian Shepherd', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Spaniel', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Schnauzer', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Golden Retriever', Dogs$Breed), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Coonhound', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Husky', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('St. Bernard', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('West Highland', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Welsh Terrier', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Belgian Sheepdog', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Shetland Sheepdog', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pug', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Sheepdog', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Collie', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Skye Terrier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Wirehaired Pointing Griffon', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Tibetan Terrier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Silky Terrier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Chow Chow', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bull Terrier', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Fox Terrier', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Whippet', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Weimaraner', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Vizsla', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Hound', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Tennesse Brindle', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Scottish Terrier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Treeing Cur', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Swedish Vallhund', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Staffordshire', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Spinone Italiano', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Spanish Mastiff', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Wheaten Terrier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Shiba Inu', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Sealyham Terr', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Schipperke', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Samoyed', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Saluki', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Ridgeback', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Rat Terrier', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Queensland Heeler', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Presa', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Port Water Dog', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pointer', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Podengo', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Corgi', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pekingese', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pbgv', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Patterdale', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Russell Terrier', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Papillon', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Otterhound', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Norwich Terrier', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Norwegian Elkhound', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Norfolk Terrier', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Newfoundland', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Mastiff', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Mexican Hairless', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Manchester Terrier', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Lowchen', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pinscher', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Leonberger', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Landseer', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Kuvasz', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Keeshond', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Jindo', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Japanese Chin', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('hound', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Setter', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Irish Terrier', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Hovawart', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Harrier', Dogs$Breed), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Swiss Mountain Dog', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Pyrenees', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Glen Of Imaal', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Finnish', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Feist', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Entlebucher', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('English Shepherd', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Dogue', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Dogo', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Doberman', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Dandie', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Coton', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Chinese', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Chesa', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Cavalier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Catahoula', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Carolina', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Cane', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Canaan', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Cairn', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bullmastiff', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bruss', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Brittany', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Boykin', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Boston', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Border', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Australian Terrier', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Blue Lacy', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Black Mouth', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bichon', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Belgian Malinois', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Tervuren', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Bedlington', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Kelpie', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Anatol', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Eskimo', Dogs$Hair), 'Long', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Alaskan', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Akita', Dogs$Hair), 'Medium', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Boerboel', Dogs$Hair), 'Short', Dogs$Hair)
Dogs$Hair = ifelse(grepl('Black', Dogs$Hair), 'Long', Dogs$Hair)

All.data = bind_rows(Cats, Dogs)

# Color
All.data$Multicolor = All.data$Color
All.data$Multicolor = ifelse(grepl('/', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Tricolor', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Calico', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Tabby', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Point', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Brindle', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Tiger', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Merle', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Tick', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Tortie', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Torbie', All.data$Multicolor), 'Yes', All.data$Multicolor)
All.data$Multicolor = ifelse(grepl('Yes', All.data$Multicolor), 'Yes', 'No')
All.data$Multicolor = ifelse(grepl('Yes', All.data$Multicolor), 1, 0)
All.data$Color = as.character(All.data$Color)
All.data$Color <- sapply(All.data$Color, 
                           function(x) strsplit(x, split = '/')[[1]][1])
All.data$Color = ifelse(grepl('Blue Tick', All.data$Color), 'Brown', All.data$Color)
All.data$Color <- sapply(All.data$Color, 
                         function(x) strsplit(x, split = ' ')[[1]][1])
All.data$Color = ifelse(grepl('Apricot', All.data$Color), 'Orange', All.data$Color)
All.data$Color = ifelse(grepl('Agouti', All.data$Color), 'Gray', All.data$Color)
All.data$Color = ifelse(grepl('Chocolate', All.data$Color), 'Brown', All.data$Color)
All.data$Color = ifelse(grepl('Ruddy', All.data$Color), 'Brown', All.data$Color)
All.data$Color = ifelse(grepl('Calico', All.data$Color), 'Tricolor', All.data$Color)
All.data$Color = ifelse(grepl('Flame', All.data$Color), 'White', All.data$Color)
All.data$Color = ifelse(grepl('Gold', All.data$Color), 'Yellow', All.data$Color)
All.data$Color = ifelse(grepl('Lilac', All.data$Color), 'Gray', All.data$Color)
All.data$Color = ifelse(grepl('Red', All.data$Color), 'Brown', All.data$Color)
All.data$Color = ifelse(grepl('Pink', All.data$Color), 'Tan', All.data$Color)
All.data$Color = ifelse(grepl('Seal', All.data$Color), 'Brown', All.data$Color)
All.data$Color = ifelse(grepl('Blue', All.data$Color), 'Gray', All.data$Color)
All.data$Color = ifelse(grepl('Lynx', All.data$Color), 'Gray', All.data$Color)
All.data$Color = ifelse(grepl('Fawn', All.data$Color), 'Yellow', All.data$Color)
All.data$Color = ifelse(grepl('Buff', All.data$Color), 'Orange', All.data$Color)
All.data$Color = ifelse(grepl('Sable', All.data$Color), 'Brown', All.data$Color)
All.data$Color = ifelse(grepl('Liver', All.data$Color), 'Gray', All.data$Color)
All.data$Color = ifelse(grepl('Silver', All.data$Color), 'Gray', All.data$Color)
All.data$Color = ifelse(grepl('Torbie', All.data$Color), 'Tricolor', All.data$Color)
All.data$Color = ifelse(grepl('Tortie', All.data$Color), 'Tricolor', All.data$Color)
All.data$Color = ifelse(grepl('Yellow', All.data$Color), 'Tan', All.data$Color)
All.data = mutate(All.data, Color = ifelse(All.data$Color == 'Cream' & All.data$AnimalType == 'Cat', 'Orange', All.data$Color))
All.data = mutate(All.data, Color = ifelse(All.data$Color == 'Cream' & All.data$AnimalType == 'Dog', 'Tan', All.data$Color))
table(All.data$Color)
# Date and Time
#install.packages('lubridate')
library(lubridate)
All.data$Hour    <- hour(All.data$DateTime)
All.data$Weekday <- wday(All.data$DateTime)
All.data$Month   <- month(All.data$DateTime)
All.data$Year    <- year(All.data$DateTime)

All.data$TimeofDay <- ifelse(All.data$Hour > 5 & All.data$Hour < 11, 'morning',
                         ifelse(All.data$Hour > 10 & All.data$Hour < 16, 'midday',
                                ifelse(All.data$Hour > 15 & All.data$Hour < 20, 'lateday', 'night')))

All.data$TimeofDay <- factor(All.data$TimeofDay, 
                         levels = c('morning', 'midday',
                                    'lateday', 'night'))

All.data$AboutToDie = (All.data$AgeinDays/365)
All.data$AboutToDie = as.integer(All.data$AboutToDie)
All.data$AboutToDie = All.data$AVERAGE.LIFESPAN..YEARS. - All.data$AboutToDie
All.data$AboutToDie = ifelse(All.data$AboutToDie <= 3, 1, 0)
#All.data = All.data[-c(17)]
#rm('Test.animals', 'Train.animals', 'PredictCatGender', 'NotCatGender')
#Test.animals = All.data[is.na(All.data$OutcomeType),]
#Train.animals = All.data[All.data$OutcomeType != '',]
#All.data = split(All.data, All.data$OutcomeType)
#ALl.data = bind_rows(All.data)
#Train.animals = ALl.data

BlackCats = Cats[Cats$Color == 'Black',]
BlackDogs = Dogs[Dogs$Color == 'Black',]


Sample = sample(c(TRUE, FALSE), nrow(All.data), replace = T, prob = c(0.7, 0.3))
Train.animals = All.data[Sample,]
Test.animals = All.data[!Sample,]
write.csv(All.data, 'Master.csv', row.names = F)
